package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="Announcement")
public class Announcement extends IdObject{
    private String text;
    private String boardId;

    public Announcement() {}

    public Announcement(String text, String boardId) {
        this.text = text;
        this.boardId = boardId;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @Override
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName="text")
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName="boardId-index", attributeName="boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @Override
    public String toString() {
        return "Announcement{" +
                "id='" + id + '\'' +
                ", text='" + text + '\'' +
                ", boardId='" + boardId + '\'' +
                '}';
    }
}
