package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="Registrar")
public class Registrar extends IdObject {
    private String offerId;
    private String OfferingType;
    private String department;
    private Long PerUnitPrice;

    public Registrar() {}

    public Registrar(String offerId, String offeringType, String department, Long perUnitPrice) {
        this.offerId = offerId;
        OfferingType = offeringType;
        this.department = department;
        PerUnitPrice = perUnitPrice;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @Override
    public String getId() {
        return id;
    }

    public String getOfferId() {
        return offerId;
    }

    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    @DynamoDBAttribute(attributeName="offeringType")
    public String getOfferingType() {
        return OfferingType;
    }

    public void setOfferingType(String offeringType) {
        OfferingType = offeringType;
    }

    @DynamoDBAttribute(attributeName="department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName="perUnitPrice")
    public Long getPerUnitPrice() {
        return PerUnitPrice;
    }

    public void setPerUnitPrice(Long perUnitPrice) {
        PerUnitPrice = perUnitPrice;
    }

    @Override
    public String toString() {
        return "Registrar{" +
                "offerId='" + offerId + '\'' +
                ", OfferingType='" + OfferingType + '\'' +
                ", department='" + department + '\'' +
                ", PerUnitPrice=" + PerUnitPrice +
                ", id='" + id + '\'' +
                '}';
    }
}
